name: Build and Deploy API to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        id: github
        uses: actions/checkout@v4

      - name: Set up Web Api .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Configure Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: SHA from GitHub commit
        id: vars
        run: |
          echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image to ACR
        env:
          ACR_REGISTRY: ${{ vars.ACR_SERVER }}
          IMAGE_TAG: ${{ steps.vars.outputs.SHA }}
        run: |
          docker build -f MasterNet.Dockerfile \
            -t $ACR_REGISTRY/netapp:$IMAGE_TAG \
            -t $ACR_REGISTRY/netapp:latest \
            .
          docker push $ACR_REGISTRY/netapp --all-tags